import type { Dossier, EvidenceItem } from "./types";

const now = new Date().toISOString();

const ev = (
  id: string,
  category: EvidenceItem["category"],
  title: string,
  status: EvidenceItem["status"],
  source: EvidenceItem["source_party"] = "user",
  note?: string,
): EvidenceItem => ({
  id,
  category,
  title,
  status,
  source_party: source,
  note,
  updated_at: now,
  received_at: status === "received" || status === "reviewed" ? "2025-09-15" : undefined,
});

export const seedDossiers: Dossier[] = [
  {
    id: "demo-northstar",
    is_demo: true,
    status: "ready_for_cpa",
    paid_unlocked: true,
    created_at: "2024-01-12T00:00:00Z",
    updated_at: now,
    inputs: {
      user_role: "founder",
      issuer_name: "Northstar Robotics",
      security_type: "founder_stock",
      acquisition_date: "2019-03-01",
      planned_exit_date: "2026-09-01",
      acquisition_method: "direct_issuer",
      shareholder_type: "individual",
      c_corp_status: "confirmed",
      gross_assets: "under",
      active_business: "confirmed",
      excluded_risk: "none",
      redemption_history: "none",
      election_83b: "yes",
      state: "CA",
      notes: "Founder shares issued at incorporation; clean cap table.",
    },
    evidence: [
      ev("n1", "purchase_agreement", "Founders' restricted stock purchase agreement", "reviewed", "counsel"),
      ev("n2", "stock_certificate", "Stock certificate #FS-001", "received", "issuer"),
      ev("n3", "election_83b", "83(b) election + USPS certified mail receipt", "reviewed", "user"),
      ev("n4", "charter", "Delaware certificate of incorporation", "received", "counsel"),
      ev("n5", "c_corp_confirmation", "Counsel letter confirming C-corp status throughout", "reviewed", "counsel"),
      ev("n6", "gross_assets", "Officer attestation: gross assets at and immediately after issuance", "received", "issuer"),
      ev("n7", "active_business", "CFO memo: active business use of assets", "received", "issuer"),
      ev("n8", "excluded_industry", "Counsel memo: not an excluded industry", "reviewed", "counsel"),
      ev("n9", "redemption", "Issuer confirmation: no redemptions in lookback windows", "received", "issuer"),
      ev("n10", "cap_table", "Cap-table extract showing original issuance", "received", "issuer"),
    ],
    letters: [],
  },
  {
    id: "demo-haloai",
    is_demo: true,
    status: "evidence_incomplete",
    paid_unlocked: false,
    created_at: "2024-06-04T00:00:00Z",
    updated_at: now,
    inputs: {
      user_role: "employee",
      issuer_name: "HaloAI",
      security_type: "iso",
      acquisition_date: "2022-11-10",
      acquisition_method: "direct_issuer",
      shareholder_type: "individual",
      c_corp_status: "likely",
      gross_assets: "unknown",
      active_business: "likely",
      excluded_risk: "none",
      redemption_history: "unknown",
      election_83b: "not_applicable",
      state: "NY",
    },
    evidence: [
      ev("h1", "purchase_agreement", "ISO grant agreement", "received", "user"),
      ev("h2", "stock_certificate", "Exercise notice + share certificate", "received", "user"),
      ev("h3", "board_approval", "Board consent — option grant", "received", "issuer"),
      ev("h4", "gross_assets", "Gross asset confirmation at issuance", "missing", "issuer"),
      ev("h5", "redemption", "Redemption history confirmation", "requested", "issuer"),
      ev("h6", "active_business", "Active business attestation", "missing", "issuer"),
    ],
    letters: [],
  },
  {
    id: "demo-brighthealth",
    is_demo: true,
    status: "evidence_incomplete",
    paid_unlocked: false,
    created_at: "2024-09-22T00:00:00Z",
    updated_at: now,
    inputs: {
      user_role: "investor",
      issuer_name: "BrightHealth Services",
      security_type: "preferred",
      acquisition_date: "2023-04-18",
      acquisition_method: "secondary",
      shareholder_type: "individual",
      c_corp_status: "confirmed",
      gross_assets: "under",
      active_business: "likely",
      excluded_risk: "yes",
      redemption_history: "unknown",
      election_83b: "not_applicable",
      state: "TX",
      notes: "Acquired via secondary; health-services exposure. Multiple structural concerns.",
    },
    evidence: [
      ev("b1", "purchase_agreement", "Secondary stock purchase agreement", "received", "user"),
      ev("b2", "excluded_industry", "Industry classification analysis", "missing", "counsel"),
      ev("b3", "cap_table", "Issuer cap-table letter", "missing", "issuer"),
    ],
    letters: [],
  },
];
