/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminDemoRouteImport } from './routes/admin-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossiersNewRouteImport } from './routes/dossiers.new'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'
import { Route as DossiersIdRequestLetterRouteImport } from './routes/dossiers.$id.request-letter'
import { Route as DossiersIdReportRouteImport } from './routes/dossiers.$id.report'
import { Route as DossiersIdEvidenceRouteImport } from './routes/dossiers.$id.evidence'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin-demo',
  path: '/admin-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersNewRoute = DossiersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DossiersRoute,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DossiersRoute,
} as any)
const DossiersIdRequestLetterRoute = DossiersIdRequestLetterRouteImport.update({
  id: '/request-letter',
  path: '/request-letter',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdReportRoute = DossiersIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdEvidenceRoute = DossiersIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DossiersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/compare': typeof CompareRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/compare': typeof CompareRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/compare': typeof CompareRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-demo'
    | '/compare'
    | '/dossiers'
    | '/pricing'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-demo'
    | '/compare'
    | '/dossiers'
    | '/pricing'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
  id:
    | '__root__'
    | '/'
    | '/admin-demo'
    | '/compare'
    | '/dossiers'
    | '/pricing'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDemoRoute: typeof AdminDemoRoute
  CompareRoute: typeof CompareRoute
  DossiersRoute: typeof DossiersRouteWithChildren
  PricingRoute: typeof PricingRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-demo': {
      id: '/admin-demo'
      path: '/admin-demo'
      fullPath: '/admin-demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/new': {
      id: '/dossiers/new'
      path: '/new'
      fullPath: '/dossiers/new'
      preLoaderRoute: typeof DossiersNewRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/dossiers/$id/request-letter': {
      id: '/dossiers/$id/request-letter'
      path: '/request-letter'
      fullPath: '/dossiers/$id/request-letter'
      preLoaderRoute: typeof DossiersIdRequestLetterRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/report': {
      id: '/dossiers/$id/report'
      path: '/report'
      fullPath: '/dossiers/$id/report'
      preLoaderRoute: typeof DossiersIdReportRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/evidence': {
      id: '/dossiers/$id/evidence'
      path: '/evidence'
      fullPath: '/dossiers/$id/evidence'
      preLoaderRoute: typeof DossiersIdEvidenceRouteImport
      parentRoute: typeof DossiersIdRoute
    }
  }
}

interface DossiersIdRouteChildren {
  DossiersIdEvidenceRoute: typeof DossiersIdEvidenceRoute
  DossiersIdReportRoute: typeof DossiersIdReportRoute
  DossiersIdRequestLetterRoute: typeof DossiersIdRequestLetterRoute
}

const DossiersIdRouteChildren: DossiersIdRouteChildren = {
  DossiersIdEvidenceRoute: DossiersIdEvidenceRoute,
  DossiersIdReportRoute: DossiersIdReportRoute,
  DossiersIdRequestLetterRoute: DossiersIdRequestLetterRoute,
}

const DossiersIdRouteWithChildren = DossiersIdRoute._addFileChildren(
  DossiersIdRouteChildren,
)

interface DossiersRouteChildren {
  DossiersIdRoute: typeof DossiersIdRouteWithChildren
  DossiersNewRoute: typeof DossiersNewRoute
}

const DossiersRouteChildren: DossiersRouteChildren = {
  DossiersIdRoute: DossiersIdRouteWithChildren,
  DossiersNewRoute: DossiersNewRoute,
}

const DossiersRouteWithChildren = DossiersRoute._addFileChildren(
  DossiersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDemoRoute: AdminDemoRoute,
  CompareRoute: CompareRoute,
  DossiersRoute: DossiersRouteWithChildren,
  PricingRoute: PricingRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
