/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AdminDemoRouteImport } from './routes/admin-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacketIdRouteImport } from './routes/packet.$id'
import { Route as HoldingIdRouteImport } from './routes/holding.$id'
import { Route as DossiersNewRouteImport } from './routes/dossiers.new'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'
import { Route as CompanyDashboardRouteImport } from './routes/company.dashboard'
import { Route as DossiersIdTrackerRouteImport } from './routes/dossiers.$id.tracker'
import { Route as DossiersIdRequestLetterRouteImport } from './routes/dossiers.$id.request-letter'
import { Route as DossiersIdReportRouteImport } from './routes/dossiers.$id.report'
import { Route as DossiersIdIssuerRouteImport } from './routes/dossiers.$id.issuer'
import { Route as DossiersIdEvidenceRouteImport } from './routes/dossiers.$id.evidence'
import { Route as DossiersIdCpaEmailRouteImport } from './routes/dossiers.$id.cpa-email'
import { Route as DossiersIdCpaRouteImport } from './routes/dossiers.$id.cpa'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin-demo',
  path: '/admin-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketIdRoute = PacketIdRouteImport.update({
  id: '/packet/$id',
  path: '/packet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingIdRoute = HoldingIdRouteImport.update({
  id: '/holding/$id',
  path: '/holding/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersNewRoute = DossiersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DossiersRoute,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DossiersRoute,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRoute,
} as any)
const DossiersIdTrackerRoute = DossiersIdTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdRequestLetterRoute = DossiersIdRequestLetterRouteImport.update({
  id: '/request-letter',
  path: '/request-letter',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdReportRoute = DossiersIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdIssuerRoute = DossiersIdIssuerRouteImport.update({
  id: '/issuer',
  path: '/issuer',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdEvidenceRoute = DossiersIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdCpaEmailRoute = DossiersIdCpaEmailRouteImport.update({
  id: '/cpa-email',
  path: '/cpa-email',
  getParentRoute: () => DossiersIdRoute,
} as any)
const DossiersIdCpaRoute = DossiersIdCpaRouteImport.update({
  id: '/cpa',
  path: '/cpa',
  getParentRoute: () => DossiersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/company': typeof CompanyRouteWithChildren
  '/compare': typeof CompareRoute
  '/demo': typeof DemoRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/holding/$id': typeof HoldingIdRoute
  '/packet/$id': typeof PacketIdRoute
  '/dossiers/$id/cpa': typeof DossiersIdCpaRoute
  '/dossiers/$id/cpa-email': typeof DossiersIdCpaEmailRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/issuer': typeof DossiersIdIssuerRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
  '/dossiers/$id/tracker': typeof DossiersIdTrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/company': typeof CompanyRouteWithChildren
  '/compare': typeof CompareRoute
  '/demo': typeof DemoRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/holding/$id': typeof HoldingIdRoute
  '/packet/$id': typeof PacketIdRoute
  '/dossiers/$id/cpa': typeof DossiersIdCpaRoute
  '/dossiers/$id/cpa-email': typeof DossiersIdCpaEmailRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/issuer': typeof DossiersIdIssuerRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
  '/dossiers/$id/tracker': typeof DossiersIdTrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-demo': typeof AdminDemoRoute
  '/company': typeof CompanyRouteWithChildren
  '/compare': typeof CompareRoute
  '/demo': typeof DemoRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/dossiers/$id': typeof DossiersIdRouteWithChildren
  '/dossiers/new': typeof DossiersNewRoute
  '/holding/$id': typeof HoldingIdRoute
  '/packet/$id': typeof PacketIdRoute
  '/dossiers/$id/cpa': typeof DossiersIdCpaRoute
  '/dossiers/$id/cpa-email': typeof DossiersIdCpaEmailRoute
  '/dossiers/$id/evidence': typeof DossiersIdEvidenceRoute
  '/dossiers/$id/issuer': typeof DossiersIdIssuerRoute
  '/dossiers/$id/report': typeof DossiersIdReportRoute
  '/dossiers/$id/request-letter': typeof DossiersIdRequestLetterRoute
  '/dossiers/$id/tracker': typeof DossiersIdTrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-demo'
    | '/company'
    | '/compare'
    | '/demo'
    | '/dossiers'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/start'
    | '/company/dashboard'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/holding/$id'
    | '/packet/$id'
    | '/dossiers/$id/cpa'
    | '/dossiers/$id/cpa-email'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/issuer'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
    | '/dossiers/$id/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-demo'
    | '/company'
    | '/compare'
    | '/demo'
    | '/dossiers'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/start'
    | '/company/dashboard'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/holding/$id'
    | '/packet/$id'
    | '/dossiers/$id/cpa'
    | '/dossiers/$id/cpa-email'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/issuer'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
    | '/dossiers/$id/tracker'
  id:
    | '__root__'
    | '/'
    | '/admin-demo'
    | '/company'
    | '/compare'
    | '/demo'
    | '/dossiers'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/settings'
    | '/sources'
    | '/start'
    | '/company/dashboard'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/holding/$id'
    | '/packet/$id'
    | '/dossiers/$id/cpa'
    | '/dossiers/$id/cpa-email'
    | '/dossiers/$id/evidence'
    | '/dossiers/$id/issuer'
    | '/dossiers/$id/report'
    | '/dossiers/$id/request-letter'
    | '/dossiers/$id/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDemoRoute: typeof AdminDemoRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  CompareRoute: typeof CompareRoute
  DemoRoute: typeof DemoRoute
  DossiersRoute: typeof DossiersRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  StartRoute: typeof StartRoute
  HoldingIdRoute: typeof HoldingIdRoute
  PacketIdRoute: typeof PacketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-demo': {
      id: '/admin-demo'
      path: '/admin-demo'
      fullPath: '/admin-demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet/$id': {
      id: '/packet/$id'
      path: '/packet/$id'
      fullPath: '/packet/$id'
      preLoaderRoute: typeof PacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holding/$id': {
      id: '/holding/$id'
      path: '/holding/$id'
      fullPath: '/holding/$id'
      preLoaderRoute: typeof HoldingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/new': {
      id: '/dossiers/new'
      path: '/new'
      fullPath: '/dossiers/new'
      preLoaderRoute: typeof DossiersNewRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/dossiers/$id/tracker': {
      id: '/dossiers/$id/tracker'
      path: '/tracker'
      fullPath: '/dossiers/$id/tracker'
      preLoaderRoute: typeof DossiersIdTrackerRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/request-letter': {
      id: '/dossiers/$id/request-letter'
      path: '/request-letter'
      fullPath: '/dossiers/$id/request-letter'
      preLoaderRoute: typeof DossiersIdRequestLetterRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/report': {
      id: '/dossiers/$id/report'
      path: '/report'
      fullPath: '/dossiers/$id/report'
      preLoaderRoute: typeof DossiersIdReportRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/issuer': {
      id: '/dossiers/$id/issuer'
      path: '/issuer'
      fullPath: '/dossiers/$id/issuer'
      preLoaderRoute: typeof DossiersIdIssuerRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/evidence': {
      id: '/dossiers/$id/evidence'
      path: '/evidence'
      fullPath: '/dossiers/$id/evidence'
      preLoaderRoute: typeof DossiersIdEvidenceRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/cpa-email': {
      id: '/dossiers/$id/cpa-email'
      path: '/cpa-email'
      fullPath: '/dossiers/$id/cpa-email'
      preLoaderRoute: typeof DossiersIdCpaEmailRouteImport
      parentRoute: typeof DossiersIdRoute
    }
    '/dossiers/$id/cpa': {
      id: '/dossiers/$id/cpa'
      path: '/cpa'
      fullPath: '/dossiers/$id/cpa'
      preLoaderRoute: typeof DossiersIdCpaRouteImport
      parentRoute: typeof DossiersIdRoute
    }
  }
}

interface CompanyRouteChildren {
  CompanyDashboardRoute: typeof CompanyDashboardRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyDashboardRoute: CompanyDashboardRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface DossiersIdRouteChildren {
  DossiersIdCpaRoute: typeof DossiersIdCpaRoute
  DossiersIdCpaEmailRoute: typeof DossiersIdCpaEmailRoute
  DossiersIdEvidenceRoute: typeof DossiersIdEvidenceRoute
  DossiersIdIssuerRoute: typeof DossiersIdIssuerRoute
  DossiersIdReportRoute: typeof DossiersIdReportRoute
  DossiersIdRequestLetterRoute: typeof DossiersIdRequestLetterRoute
  DossiersIdTrackerRoute: typeof DossiersIdTrackerRoute
}

const DossiersIdRouteChildren: DossiersIdRouteChildren = {
  DossiersIdCpaRoute: DossiersIdCpaRoute,
  DossiersIdCpaEmailRoute: DossiersIdCpaEmailRoute,
  DossiersIdEvidenceRoute: DossiersIdEvidenceRoute,
  DossiersIdIssuerRoute: DossiersIdIssuerRoute,
  DossiersIdReportRoute: DossiersIdReportRoute,
  DossiersIdRequestLetterRoute: DossiersIdRequestLetterRoute,
  DossiersIdTrackerRoute: DossiersIdTrackerRoute,
}

const DossiersIdRouteWithChildren = DossiersIdRoute._addFileChildren(
  DossiersIdRouteChildren,
)

interface DossiersRouteChildren {
  DossiersIdRoute: typeof DossiersIdRouteWithChildren
  DossiersNewRoute: typeof DossiersNewRoute
}

const DossiersRouteChildren: DossiersRouteChildren = {
  DossiersIdRoute: DossiersIdRouteWithChildren,
  DossiersNewRoute: DossiersNewRoute,
}

const DossiersRouteWithChildren = DossiersRoute._addFileChildren(
  DossiersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDemoRoute: AdminDemoRoute,
  CompanyRoute: CompanyRouteWithChildren,
  CompareRoute: CompareRoute,
  DemoRoute: DemoRoute,
  DossiersRoute: DossiersRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  StartRoute: StartRoute,
  HoldingIdRoute: HoldingIdRoute,
  PacketIdRoute: PacketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
